version: '3'
services:
  db:
    image: mysql:8.0.32
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "3306:${RDS_PORT}"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    environment:
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      RAILS_ENV: development
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/grow-api
      - log-data:/grow-api/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  log-data:
  db-data: