version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "3306:${RDS_PORT}"
  app:
    build: .
    environment:
      DB_USER: ${RDS_USERNAME}
      DB_PASSWORD: ${RDS_PASSWORD}
      DB_HOST: ${RDS_HOSTNAME}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      RAILS_ENV: production
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true